app/routes/cliente.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from database import select_all_clientes, select_cliente_for_codi, insert_cliente, update_cliente, delete_cliente
import pdfkit
from pathlib import Path
import os

BASE_DIR = Path(os.path.join(os.path.dirname(__file__))).parent.parent

cliente = Blueprint('cliente', __name__, url_prefix='/cliente')

@cliente.route('/', methods=['GET'])
def Index():
    data = select_all_clientes()   
    return render_template('/cliente/index.html', clientes=data)

@cliente.route('/insertar_cliente', methods=['POST'])
def insertar_cliente():
    cedula = request.form['cedula']
    nombre = request.form['nombre']        
    apellido = request.form['apellido']
    direccion = request.form['direccion']
    telefono = request.form['telefono']
    email = request.form['email']    
    try:
        insert_cliente(cedula, nombre, apellido, direccion, telefono, email)
        flash('Cliente insertado con exito')
    except Exception as e:        
        flash('Error en el Pedido, vuelva a intentaro y revise los datos.')
        print(e)
    return redirect(url_for('.Index'))

@cliente.route('/actualizar_cliente/<string:codi>', methods=['GET', 'POST'])
def actualizar_cliente(codi):
    if( request.method == 'GET'):
        data = select_cliente_for_codi(codi)
        return render_template('/cliente/editar.html', cliente=data)
    elif( request.method == 'POST'):
        cedula = request.form['cedula']
        nombre = request.form['nombre']        
        apellido = request.form['apellido']
        direccion = request.form['direccion']
        telefono = request.form['telefono']
        email = request.form['email']    
        try:    
            update_cliente(codi, cedula, nombre, apellido, direccion, telefono, email)
            flash('Cliente editado con exito')
        except Exception as e:
            print(e)
        return redirect(url_for('.Index'))

@cliente.route('/eliminar_cliente/<string:codi>', methods=['POST', 'GET'])
def eliminar_cliente(codi:int):    
    try:
        delete_cliente(codi)
        flash('Cliente eliminado con exito')
    except Exception as e:
        flash('El Cliente esta enlazado con un Pedido. Elimine el pedido primero.')
        print(e)
    return redirect(url_for('.Index'))
    
@cliente.route('/reporte_cliente', methods=['GET'])
def generar_reporte_cli():
    print(BASE_DIR / "reports")    
    path_wkhtmltopdf = r'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe'
    config = pdfkit.configuration(wkhtmltopdf=path_wkhtmltopdf)
    pdfkit.from_url("http://127.0.0.1:3000/cliente/", BASE_DIR / f"reports/cliente/out.pdf", configuration=config)
    return redirect(url_for('.Index'))

app/routes/pedido.py
from datetime import datetime
from time import sleep
from flask import Blueprint, request, render_template, redirect, url_for, flash
from database import (
    select_all_celulares,
    select_all_pedidos,
    select_pedido_for_codi,
    select_detalle_for_codi_pedi,
    update_pedido,
    update_detalle,
    delete_detalle,
    delete_pedido,
    select_cliente_codi_for_cedu_y_nomb,
    select_direccion_envio_codi_for_clpr_y_refe,
    select_pedido_codi_for_clie_y_dien,
    insert_cliente,
    insert_direccion_envio,
    insert_pedido,
    insert_detalle,
    calcular_subtotal_producto,
    calcular_iva,
)
import pdfkit
from pathlib import Path
import os

BASE_DIR = Path(os.path.join(os.path.dirname(__file__))).parent.parent

pedido = Blueprint("pedido", __name__, url_prefix="/pedido")


@pedido.route("/", methods=["GET"])
def Index():
    data = select_all_pedidos()
    return render_template("/pedido/index.html", pedidos=data)


@pedido.route("/insertar_pedido", methods=["GET", "POST"])
def insertar_pedido():
    data = select_all_celulares()

    if request.method == "GET":
        return render_template("/pedido/ingresar.html", celulares=data)
    elif request.method == "POST":
        # Datos del cliente
        cedula = request.form["cedula"]
        nombre = request.form["nombre"]
        apellido = request.form["apellido"]
        direccion = request.form["direccion"]
        telefono = request.form["telefono"]
        email = request.form["email"]
        # Datos de la direccion de envio
        calle_pri = request.form["calle_pri"]
        calle_sec = request.form["calle_sec"]
        nume_depa = request.form["nume_depa"]
        referencia = request.form["referencia"]
        ciudad = request.form["ciudad"]
        provincia = request.form["provincia"]
        codi_postal = request.form["codi_postal"]
        # Datos del Pedido
        total_pedi = 0
        subtotal_por_produ = []
        cantidadTemp = {}
        fecha_pedi = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        selected_celu = request.form.getlist("celulares")
        observa = request.form["observa"]
        # Celulares selccionados y cantidad
        for celu in selected_celu:
            comodin = f"celular_{celu}"
            cantidad = request.form[comodin]
            cantidadTemp[celu] = cantidad
            for c in data:
                if c[0] == int(celu):
                    total_pedi = (c[9] * int(cantidad)) + total_pedi
                    subtotal_por_produ.append(
                        calcular_subtotal_producto(int(cantidad), c[9])
                    )
                    break
        try:
            iva = calcular_iva(total_pedi, 12)
            #===========================================================
            insert_cliente(cedula, nombre, apellido, direccion, telefono, email)
            insert_direccion_envio(
                calle_pri,
                calle_sec,
                nume_depa,
                referencia,
                ciudad,
                provincia,
                codi_postal,
            )
            codi_clie = select_cliente_codi_for_cedu_y_nomb(cedula, nombre)            
            codi_dien = select_direccion_envio_codi_for_clpr_y_refe(
                calle_pri, referencia
            )            
            insert_pedido(fecha_pedi, total_pedi, observa, codi_clie, codi_dien)            
            codi_pedi = select_pedido_codi_for_clie_y_dien(codi_clie, codi_dien)                                    
            sleep(0.5)
            for celu, canti in cantidadTemp.items():
                insert_detalle(canti, celu, codi_pedi)
            #===========================================================

            flash("Pedido realizado con exito")
            flash(f"El valor a pagar es de ${total_pedi}")
        except Exception as e:
            print(e)
        return render_template(
            "/pedido/resumen.html",
            subtotales=subtotal_por_produ,
            total=total_pedi,
            iva=iva,
        )

@pedido.route("/actualizar_pedido/<string:codi>", methods=["GET", "POST"])
def actualizar_pedido(codi):
    if request.method == "GET":
        data1 = select_pedido_for_codi(codi)
        data2 = select_detalle_for_codi_pedi(codi)
        return render_template("/pedido/editar.html", pedido=data1, detalle=data2)
    elif request.method == "POST":
        codes = select_detalle_for_codi_pedi(codi)
        fecha_pedido = request.form["fecha_pedido"]
        observ = request.form["observ"]
        total_pedido = 0
        for code in codes:
            comodin = f"celular_{code[6]}"
            cantidad = request.form[comodin]
            total_pedido = total_pedido + (int(cantidad) * code[5])
            try:
                update_detalle(code[1], cantidad, code[6], code[0])
            except Exception as e:
                print(e)
        try:
            update_pedido(
                codi, fecha_pedido, total_pedido, observ, codes[0][7], codes[0][8]
            )
            flash("Pedido editado con exito")
        except Exception as e:
            print(e)
        return redirect(url_for(".Index"))


@pedido.route("/eliminar_pedido/<string:codi>", methods=["POST", "GET"])
def eliminar_pedido(codi: int):
    codes = select_detalle_for_codi_pedi(codi)
    try:
        for code in codes:
            delete_detalle(code[1])
        delete_pedido(codi)
        flash("Pedido eliminado con exito")
    except Exception as e:
        print(e)
    return redirect(url_for(".Index"))


@pedido.route("/eliminar_detalle/<string:codi>", methods=["POST", "GET"])
def eliminar_detalle(codi: int):
    try:
        delete_detalle(codi)
        flash("Celular eliminado con exito")
    except Exception as e:
        print(e)
    return redirect(url_for(".Index"))

@pedido.route('/reporte_pedido', methods=['GET'])
def generar_reporte_ped():
    print(BASE_DIR / "reports")    
    path_wkhtmltopdf = r'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe'
    config = pdfkit.configuration(wkhtmltopdf=path_wkhtmltopdf)
    pdfkit.from_url("http://127.0.0.1:3000/pedido/", BASE_DIR / f"reports/pedido/out.pdf", configuration=config)
    return redirect(url_for('.Index'))

app/templates/cliente/editar.html
{% extends 'base.html' %}
{% block body %}
<div class="container text-center position-absolute top-50 start-50 translate-middle">
    <div class="row align-items-center">        
        <form method="post" action="{{ url_for('.actualizar_cliente', codi=cliente[0]) }}">
            <div class="container text-center">
              <div class="row align-items-start">
                <div class="col">
                  <label for="id_cedula" class="form-label">Cedula</label>
                  <input type="text" class="form-control" id="id_cedula" name="cedula" value="{{cliente[1]}}">
                  <label for="id_nombre" class="form-label">Nombre</label>
                  <input type="text" class="form-control" id="id_nombre" name="nombre" value="{{cliente[2]}}">
                  <label for="id_apellido" class="form-label">Apellido</label>
                  <input type="text" class="form-control" id="id_apellido" name="apellido" value="{{cliente[3]}}">
                </div>
                <div class="col">
                  <label for="id_direccion" class="form-label">Direccion</label>
                  <input type="text" class="form-control" id="id_direccion" name="direccion" value="{{cliente[4]}}">
                  <label for="id_telefono" class="form-label">Telefono</label>
                  <input type="text" class="form-control" id="id_telefono" name="telefono" value="{{cliente[5]}}">
                  <label for="id_email" class="form-label">Email</label>
                  <input type="email" class="form-control" id="id_email" name="email" value="{{cliente[6]}}">
                </div>                   
              </div>
            </div>
            <div id="emailHelp" class="form-text">Los datos del Cliente serán actualizados.</div>
            <button type="submit" class="btn btn-primary">Editar Datos</button>
          </form>          
    </div>
    <br>
    <a href="{{ url_for('.Index') }}" class="btn btn-primary">Regresar a la Lista</a>
    <a href="{{ url_for('pedido.insertar_pedido') }}" class="btn btn-primary">Regresar al menu Principal</a>
</div>
{% endblock %}

app/templates/cliente/index.html
{% extends 'base.html' %}
{% block body %}

{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages%}
<div class="alert alert-success" role="alert">
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

<div class="container text-center">
  <div class="row align-items-start">
    {% if clientes %}
    <div class="col">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Cedula</th>
            <th scope="col">Nombre</th>
            <th scope="col">Apellido</th>
            <th scope="col">Direccion</th>
            <th scope="col">Telefono</th>
            <th scope="col">Email</th>
            <th scope="col">---</th>
            <th scope="col">---</th>
          </tr>
        </thead>
        <tbody>
          {% for cliente in clientes %}
          <tr>
            <th scope="row" class="text-center">{{ cliente[1] }}</th>
            <td class="text-center">{{ cliente[2] }}</td>
            <td class="text-center">{{ cliente[3] }}</td>
            <td class="text-center">{{ cliente[4] }}</td>
            <td class="text-center">{{ cliente[5] }}</td>
            <td class="text-center">{{ cliente[6] }}</td>
            <td><a href="actualizar_cliente/{{ cliente[0] }}" class="btn btn-primary">Editar</a></td>
            <td><a href="eliminar_cliente/{{ cliente[0] }}" class="btn btn-primary">Eliminar</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% else %}
    <div class="alert alert-info" role="alert">
      Lista Vacia, no hay Clientes Registrados.
    </div>
    {% endif %}


    <div class="col">
      <div class="position-fixed m-5">
        <h1>Registrar Cliente</h1>
        <form method="post" action="{{ url_for('.insertar_cliente') }}">
          <div class="container text-center">
            <div class="row align-items-start">
              <label for="id_nombre" class="form-label">Nombre</label>
              <input type="text" class="form-control" id="id_nombre" name="nombre">
              <label for="id_apellido" class="form-label">Apellido</label>
              <input type="text" class="form-control" id="id_apellido" name="apellido">
              <div class="col">
                <label for="id_cedula" class="form-label">Cedula</label>
                <input type="text" class="form-control" id="id_cedula" name="cedula">
                <label for="id_direccion" class="form-label">Direccion</label>
                <input type="text" class="form-control" id="id_direccion" name="direccion">
              </div>
              <div class="col">
                <label for="id_telefono" class="form-label">Telefono</label>
                <input type="text" class="form-control" id="id_telefono" name="telefono">
                <label for="id_email" class="form-label">Email</label>
                <input type="email" class="form-control" id="id_email" name="email">
              </div>
            </div>
          </div>
          <div id="emailHelp" class="form-text">Los datos del Cliente seran registrados.</div>
          <button type="submit" class="btn btn-primary">Agregar Datos <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
          </svg></button>
        </form>
      </div>
    </div>
    <a href="{{url_for('cliente.generar_reporte_cli')}}">Generar reporte PDF</a>
  </div>
</div>
{% endblock %}