app/routes/pedido.py
from datetime import datetime
from time import sleep
from flask import Blueprint, request, render_template, redirect, url_for, flash
from database import (
    select_all_celulares,
    select_all_pedidos,
    select_pedido_for_codi,
    select_detalle_for_codi_pedi,
    update_pedido,
    update_detalle,
    delete_detalle,
    delete_pedido,
    select_cliente_codi_for_cedu_y_nomb,
    select_direccion_envio_codi_for_clpr_y_refe,
    select_pedido_codi_for_clie_y_dien,
    insert_cliente,
    insert_direccion_envio,
    insert_pedido,
    insert_detalle,
    calcular_subtotal_producto,
    calcular_iva,
)
import pdfkit
from pathlib import Path
import os

BASE_DIR = Path(os.path.join(os.path.dirname(__file__))).parent.parent

pedido = Blueprint("pedido", __name__, url_prefix="/pedido")


@pedido.route("/", methods=["GET"])
def Index():
    data = select_all_pedidos()
    return render_template("/pedido/index.html", pedidos=data)


@pedido.route("/insertar_pedido", methods=["GET", "POST"])
def insertar_pedido():
    data = select_all_celulares()

    if request.method == "GET":
        return render_template("/pedido/ingresar.html", celulares=data)
    elif request.method == "POST":
        # Datos del cliente
        cedula = request.form["cedula"]
        nombre = request.form["nombre"]
        apellido = request.form["apellido"]
        direccion = request.form["direccion"]
        telefono = request.form["telefono"]
        email = request.form["email"]
        # Datos de la direccion de envio
        calle_pri = request.form["calle_pri"]
        calle_sec = request.form["calle_sec"]
        nume_depa = request.form["nume_depa"]
        referencia = request.form["referencia"]
        ciudad = request.form["ciudad"]
        provincia = request.form["provincia"]
        codi_postal = request.form["codi_postal"]
        # Datos del Pedido
        total_pedi = 0
        subtotal_por_produ = []
        cantidadTemp = {}
        fecha_pedi = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        selected_celu = request.form.getlist("celulares")
        observa = request.form["observa"]
        # Celulares selccionados y cantidad
        for celu in selected_celu:
            comodin = f"celular_{celu}"
            cantidad = request.form[comodin]
            cantidadTemp[celu] = cantidad
            for c in data:
                if c[0] == int(celu):
                    total_pedi = (c[9] * int(cantidad)) + total_pedi
                    subtotal_por_produ.append(
                        calcular_subtotal_producto(int(cantidad), c[9])
                    )
                    break
        try:
            iva = calcular_iva(total_pedi, 12)
            #===========================================================
            insert_cliente(cedula, nombre, apellido, direccion, telefono, email)
            insert_direccion_envio(
                calle_pri,
                calle_sec,
                nume_depa,
                referencia,
                ciudad,
                provincia,
                codi_postal,
            )
            codi_clie = select_cliente_codi_for_cedu_y_nomb(cedula, nombre)            
            codi_dien = select_direccion_envio_codi_for_clpr_y_refe(
                calle_pri, referencia
            )            
            insert_pedido(fecha_pedi, total_pedi, observa, codi_clie, codi_dien)            
            codi_pedi = select_pedido_codi_for_clie_y_dien(codi_clie, codi_dien)                                    
            sleep(0.5)
            for celu, canti in cantidadTemp.items():
                insert_detalle(canti, celu, codi_pedi)
            #===========================================================

            flash("Pedido realizado con exito")
            flash(f"El valor a pagar es de ${total_pedi}")
        except Exception as e:
            print(e)
        return render_template(
            "/pedido/resumen.html",
            subtotales=subtotal_por_produ,
            total=total_pedi,
            iva=iva,
        )

@pedido.route("/actualizar_pedido/<string:codi>", methods=["GET", "POST"])
def actualizar_pedido(codi):
    if request.method == "GET":
        data1 = select_pedido_for_codi(codi)
        data2 = select_detalle_for_codi_pedi(codi)
        return render_template("/pedido/editar.html", pedido=data1, detalle=data2)
    elif request.method == "POST":
        codes = select_detalle_for_codi_pedi(codi)
        fecha_pedido = request.form["fecha_pedido"]
        observ = request.form["observ"]
        total_pedido = 0
        for code in codes:
            comodin = f"celular_{code[6]}"
            cantidad = request.form[comodin]
            total_pedido = total_pedido + (int(cantidad) * code[5])
            try:
                update_detalle(code[1], cantidad, code[6], code[0])
            except Exception as e:
                print(e)
        try:
            update_pedido(
                codi, fecha_pedido, total_pedido, observ, codes[0][7], codes[0][8]
            )
            flash("Pedido editado con exito")
        except Exception as e:
            print(e)
        return redirect(url_for(".Index"))


@pedido.route("/eliminar_pedido/<string:codi>", methods=["POST", "GET"])
def eliminar_pedido(codi: int):
    codes = select_detalle_for_codi_pedi(codi)
    try:
        for code in codes:
            delete_detalle(code[1])
        delete_pedido(codi)
        flash("Pedido eliminado con exito")
    except Exception as e:
        print(e)
    return redirect(url_for(".Index"))


@pedido.route("/eliminar_detalle/<string:codi>", methods=["POST", "GET"])
def eliminar_detalle(codi: int):
    try:
        delete_detalle(codi)
        flash("Celular eliminado con exito")
    except Exception as e:
        print(e)
    return redirect(url_for(".Index"))

@pedido.route('/reporte_pedido', methods=['GET'])
def generar_reporte_ped():
    print(BASE_DIR / "reports")    
    path_wkhtmltopdf = r'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe'
    config = pdfkit.configuration(wkhtmltopdf=path_wkhtmltopdf)
    pdfkit.from_url("http://127.0.0.1:3000/pedido/", BASE_DIR / f"reports/pedido/out.pdf", configuration=config)
    return redirect(url_for('.Index'))

app/templates/pedido/editar.html
{% extends 'base.html' %}
{% block body %}

<div class="container text-center position-absolute top-50 start-50 translate-middle" >
  <div class="row align-items-center">
    <form method="post" action="{{ url_for('.actualizar_pedido', codi=pedido[0]) }}">
      <div class="container text-center">
        <div class="row align-items-start" >
          <div class="col">
            <label for="id_calle_pri" class="form-label">Fecha del Pedido</label>
            <input type="fecha_pedido" class="form-control" id="id_fecha_pedido" name="fecha_pedido" value="{{pedido[1]}}" readonly>
            <label for="id_observ" class="form-label">Observacion</label>
            <input type="text" class="form-control" id="id_observ" name="observ" value="{{pedido[3]}}">
            <label for="id_valor_tota" class="form-label">Valor Total</label>
            <input type="text" class="form-control" id="id_valor_tota" name="valor_tota" value="{{pedido[2]}}" disabled>
          </div>
          <div class="col">
            <label for="id_celu_pedi" class="form-label">Celulares Pedidos</label>
            {% for deta in detalle %}                      
            <div class="input-group mb-3" id="id_celu_pedi">
              <span class="input-group-text">{{ deta[3] }} - {{ deta[4] }}</span>
              <input type="text" aria-label="cantidad" class="form-control" name="celular_{{ deta [6] }}" value="{{ deta[2] }}" placeholder="Cantidad" required>              
              <span class="input-group-text">x ${{ deta[5] }}</span>
              <a href="{{ url_for('.eliminar_detalle', codi=deta[1]) }}" class="btn btn-primary">Eliminar</a>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <div id="emailHelp" class="form-text">Los datos del Pedido serán actualizados.</div>
      <button type="submit" class="btn btn-primary">Editar Datos</button>
    </form>
  </div>
  <br>
  <a href="{{ url_for('.Index') }}" class="btn btn-primary">Regresar a la Lista</a>
  <a href="{{ url_for('pedido.insertar_pedido') }}" class="btn btn-primary">Regresar al menu Principal</a>
</div>
{% endblock %}

app/templates/pedido/index.html
{% extends 'base.html' %}
{% block body %}

{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages%}
<div class="alert alert-success" role="alert">
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

<div class="container-fluid text-center" >
  <div class="row align-items-start">
    {% if pedidos %}
    <h1>Pedidos Realizados</h1>
    <div class="col">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Numero de Pedido</th> 
            <th scope="col">Fecha de Pedido</th>            
            <th scope="col">Observaciones</th>
            <th scope="col">Nombre de Cliente</th> 
            <th scope="col">Apellido de Cliente</th> 
            <th scope="col">Cedula de Cliente</th> 
            <th scope="col">Calle Principal</th> 
            <th scope="col">Calle Secundaria</th> 
            <th scope="col">Provincia</th>             
            <th scope="col">Ciudad</th> 
            <th scope="col">Marca</th>
            <th scope="col">Modelo</th>
            <th scope="col">Precio del Celular</th> 
            <th scope="col">Subtotal por Producto</th> 
            <th scope="col">Cantidad del Pedido</th>
            <th scope="col">IVA</th>
            <th scope="col">Total del Pedido</th>            
          </tr>
          <tr>
            
          </tr>
        </thead>
        <tbody>
          {% for pedido in pedidos %}
          <tr>
            <th scope="row" class="text-center">0000 - {{ pedido[0] }}</th>
            <td class="text-center">{{ pedido[1] }}</td>
            <td class="text-center">{{ pedido[3] }}</td>
            <td class="text-center">{{ pedido[13] }}</td>
            <td class="text-center">{{ pedido[14] }}</td>
            <td class="text-center">{{ pedido[12] }}</td>
            <td class="text-center">{{ pedido[8] }}</td>
            <td class="text-center">{{ pedido[9] }}</td>
            <td class="text-center">{{ pedido[10] }}</td>
            <td class="text-center">{{ pedido[11] }}</td>
            <td class="text-center">{{ pedido[5] }}</td>
            <td class="text-center">{{ pedido[6] }}</td>
            <td class="text-center">{{ pedido[7] }}</td>            
            <td class="text-center">{{ pedido[15] }}</td>          
            <td class="text-center">{{ pedido[4] }}</td>                                    
            <td class="text-center">{{ pedido[16] }}</td>  
            <td class="text-center">{{ pedido[2] }}</td>            
          </tr>
          <tr>
            <th scope="col">Acciones</th>                        
            <th scope="col">---</th>                        
          </tr>
          <tr>
            <td><a href="actualizar_pedido/{{ pedido[0] }}" class="btn btn-primary">Editar</a></td>
            <td><a href="eliminar_pedido/{{ pedido[0] }}" class="btn btn-primary">Eliminar</a></td>             
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <a href="{{url_for('pedido.generar_reporte_ped')}}">Generar reporte PDF</a>
    {% else %}
    <div class="alert alert-info" role="alert">
      Lista Vacia, no hay Pedidos Registrados.
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

app/templates/pedido/ingresar.html
{% extends 'base.html' %}
{% block body %}

{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages%}
<div class="alert alert-success" role="alert">
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

<br>
<div class="container">
  <img src="{{ url_for('static', filename='samsung.png') }}" alt="" width="120" height="60" class="float-end">
  <img src="{{ url_for('static', filename='apple.png') }}" alt="" width="50" height="60" class="float-end">
  <img src="{{ url_for('static', filename='xiaomi.png') }}" alt="" width="50" height="60">
  <img src="{{ url_for('static', filename='infinix.png') }}" alt="" width="120" height="60">
</div>
<div class="container text-center">
  <div class="row align-items-center">
    <h1>Realizar Pedido</h1>
    <form method="post" action="{{ url_for('.insertar_pedido')}}">
      <div class="container text-center">
        <div class="row align-items-start">
          <div class="col">
            <h3>Celulares Disponibles</h3>
            {% if celulares %}
            <div class="form-check">
              {% for celular in celulares %}
              <div class="input-group mb-3">
                <div class="input-group-text">
                  <input class="form-check-input mt-0" type="checkbox" value="{{ celular[0] }}"
                    aria-label="Checkbox for following text input" name="celulares">
                </div>
                <span class="input-group-text text-primary-emphasis">{{celular[1]}} - {{celular[2]}}</span>
                <input type="text" class="form-control" aria-label="Text input with checkbox" placeholder="Cantidad"
                  name="celular_{{ celular[0] }}">
                <span class="input-group-text text-success">Precio - $</span>
                <span class="input-group-text">{{ celular[9] }}</span>
              </div>
              {% endfor %}
            </div>
            {% else %}
            <div class="alert alert-info" role="alert">
              Lista Vacia, no hay Celulares Registrados.
            </div>
            {% endif %}
          </div>
          <label for="id_observa" class="form-label">Observaciones del Pedido</label>
          <input type="text" class="form-control" id="id_observa" name="observa">
        </div>
      </div>
      <hr>
      <div class="container text-center">
        <h3>Datos del Cliente</h3>
        <div class="row align-items-start">
          <div class="col">
            <label for="id_nombre" class="form-label">Nombre</label>
            <input type="text" class="form-control" id="id_nombre" name="nombre">
            <label for="id_email" class="form-label">Email</label>
            <input type="email" class="form-control" id="id_email" name="email">
          </div>
          <div class="col">
            <label for="id_apellido" class="form-label">Apellido</label>
            <input type="text" class="form-control" id="id_apellido" name="apellido">
            <label for="id_telefono" class="form-label">Telefono</label>
            <input type="text" class="form-control" id="id_telefono" name="telefono">
          </div>
          <div class="col">
            <label for="id_cedula" class="form-label">Cedula</label>
            <input type="text" class="form-control" id="id_cedula" name="cedula">
            <label for="id_direccion" class="form-label">Direccion</label>
            <input type="text" class="form-control" id="id_direccion" name="direccion">
          </div>
        </div>
      </div>
      <hr>
      <div class="container text-center">
        <h3>Datos de la Direccion de Envio</h3>
        <div class="row align-items-start">
          <label for="id_calle_pri" class="form-label">Calle Princpial</label>
          <input type="text" class="form-control" id="id_calle_pri" name="calle_pri">
          <div class="col">
            <label for="id_calle_sec" class="form-label">Calle Secundaria</label>
            <input type="text" class="form-control" id="id_calle_sec" name="calle_sec">
            <label for="id_ciudad" class="form-label">Ciudad</label>
            <input type="text" class="form-control" id="id_ciudad" name="ciudad">
            <label for="id_provincia" class="form-label">Provincia</label>
            <input type="text" class="form-control" id="id_provincia" name="provincia">
          </div>
          <div class="col">
            <label for="id_nume_depa" class="form-label">Numero de Departamento</label>
            <input type="text" class="form-control" id="id_nume_depa" name="nume_depa">
            <label for="id_referencia" class="form-label">Referencia</label>
            <input type="text" class="form-control" id="id_referencia" name="referencia">
            <label for="id_codi_postal" class="form-label">Codigo Postal</label>
            <input type="text" class="form-control" id="id_codi_postal" name="codi_postal">
          </div>
        </div>
        <div id="emailHelp" class="form-text">El pedido sera realizado.</div>
        <button type="submit" class="btn btn-primary">Realizar Pedido <svg xmlns="http://www.w3.org/2000/svg" width="16"
            height="16" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
            <path
              d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z" />
          </svg></button>
    </form>
  </div>
  <br>
</div>
<div>
  <br>
</div>

{% endblock %}

app/templates/pedido/resumen.html
{% extends 'base.html' %}
{% block body %}
<div class="container text-center">
    <div class="row align-items-start">        
        <div class="col">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Subtotal Por Telefono</th>
                    </tr>
                </thead>
                <tbody>
                    {% for subtotal in subtotales %}
                    <tr>
                        <th scope="row" class="text-center">{{ subtotal }}</th>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <label for="id_observa" class="form-label">Subtotal = </label>
            <label for="id_observa" class="form-label text-primary">{{ total-iva }}</label><br>
            <label for="id_observa" class="form-label">IVA = </label>
            <label for="id_observa" class="form-label text-primary">{{ iva }}</label><br>
            <label for="id_observa" class="form-label">Total del Pedido = </label>
            <label for="id_observa" class="form-label text-primary">{{ total }}</label>
        </div>

        
        <a href="{{ url_for('pedido.insertar_pedido') }}" class="btn btn-primary">Regresar al menu Principal</a>
    </div>
</div>
{% endblock %}