app/routes/direccion_envio.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from database import (
    direccion_envio,
    select_all_direccion_envio,
    select_direccion_envio_for_codi,
    insert_direccion_envio,
    update_direccion_envio,
    delete_direccion_envio
)
import pdfkit
from pathlib import Path
import os

BASE_DIR = Path(os.path.join(os.path.dirname(__file__))).parent.parent

direccion_envio = Blueprint('direccion_envio', __name__, url_prefix='/direccion_envio')

@direccion_envio.route('/', methods=['GET'])
def Index():
    data = select_all_direccion_envio()   
    return render_template('/direccion_envio/index.html', direcciones_envio=data)

@direccion_envio.route('/insertar_direccion_envio', methods=['POST'])
def insertar_direccion_envio():
    calle_pri = request.form['calle_pri']
    calle_sec = request.form['calle_sec']        
    nume_depa = request.form['nume_depa']
    referencia = request.form['referencia']
    ciudad = request.form['ciudad']
    provincia = request.form['provincia']
    codi_postal = request.form['codi_postal']    
    try:
        insert_direccion_envio(calle_pri, calle_sec, nume_depa, referencia, ciudad, provincia, codi_postal)
        flash('Direccion de Envio insertado con exito')
    except Exception as e:                
        print(e)
    return redirect(url_for('.Index'))

@direccion_envio.route('/actualizar_direccion_envio/<string:codi>', methods=['GET', 'POST'])
def actualizar_direccion_envio(codi):
    if( request.method == 'GET'):
        data = select_direccion_envio_for_codi(codi)
        return render_template('/direccion_envio/editar.html', direccion_envio=data)
    elif( request.method == 'POST'):
        calle_pri = request.form['calle_pri']
        calle_sec = request.form['calle_sec']        
        nume_depa = request.form['nume_depa']
        referencia = request.form['referencia']
        ciudad = request.form['ciudad']
        provincia = request.form['provincia']
        codi_postal = request.form['codi_postal']           
        try:    
            update_direccion_envio(codi, calle_pri, calle_sec, nume_depa, referencia, ciudad, provincia, codi_postal)
            flash('Direccion de Envio editado con exito')
        except Exception as e:
            print(e)
        return redirect(url_for('.Index'))

@direccion_envio.route('/eliminar_direccion_envio/<string:codi>', methods=['POST', 'GET'])
def eliminar_direccion_envio(codi:int):    
    try:
        delete_direccion_envio(codi)
        flash('Direccion de Envio eliminado con exito')
    except Exception as e:
        flash('La Direccion de Envio esta enlazado con un Pedido. Elimine el pedido primero.')
        print(e)
    return redirect(url_for('.Index'))

@direccion_envio.route('/reporte_direccion_envio', methods=['GET'])
def generar_reporte_die():
    print(BASE_DIR / "reports")    
    path_wkhtmltopdf = r'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe'
    config = pdfkit.configuration(wkhtmltopdf=path_wkhtmltopdf)
    pdfkit.from_url("http://127.0.0.1:3000/direccion_envio/", BASE_DIR / f"reports/direccion_envio/out.pdf", configuration=config)
    return redirect(url_for('.Index'))

app/routes/pedido.py
from datetime import datetime
from time import sleep
from flask import Blueprint, request, render_template, redirect, url_for, flash
from database import (
    select_all_celulares,
    select_all_pedidos,
    select_pedido_for_codi,
    select_detalle_for_codi_pedi,
    update_pedido,
    update_detalle,
    delete_detalle,
    delete_pedido,
    select_cliente_codi_for_cedu_y_nomb,
    select_direccion_envio_codi_for_clpr_y_refe,
    select_pedido_codi_for_clie_y_dien,
    insert_cliente,
    insert_direccion_envio,
    insert_pedido,
    insert_detalle,
    calcular_subtotal_producto,
    calcular_iva,
)
import pdfkit
from pathlib import Path
import os

BASE_DIR = Path(os.path.join(os.path.dirname(__file__))).parent.parent

pedido = Blueprint("pedido", __name__, url_prefix="/pedido")


@pedido.route("/", methods=["GET"])
def Index():
    data = select_all_pedidos()
    return render_template("/pedido/index.html", pedidos=data)


@pedido.route("/insertar_pedido", methods=["GET", "POST"])
def insertar_pedido():
    data = select_all_celulares()

    if request.method == "GET":
        return render_template("/pedido/ingresar.html", celulares=data)
    elif request.method == "POST":
        # Datos del cliente
        cedula = request.form["cedula"]
        nombre = request.form["nombre"]
        apellido = request.form["apellido"]
        direccion = request.form["direccion"]
        telefono = request.form["telefono"]
        email = request.form["email"]
        # Datos de la direccion de envio
        calle_pri = request.form["calle_pri"]
        calle_sec = request.form["calle_sec"]
        nume_depa = request.form["nume_depa"]
        referencia = request.form["referencia"]
        ciudad = request.form["ciudad"]
        provincia = request.form["provincia"]
        codi_postal = request.form["codi_postal"]
        # Datos del Pedido
        total_pedi = 0
        subtotal_por_produ = []
        cantidadTemp = {}
        fecha_pedi = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        selected_celu = request.form.getlist("celulares")
        observa = request.form["observa"]
        # Celulares selccionados y cantidad
        for celu in selected_celu:
            comodin = f"celular_{celu}"
            cantidad = request.form[comodin]
            cantidadTemp[celu] = cantidad
            for c in data:
                if c[0] == int(celu):
                    total_pedi = (c[9] * int(cantidad)) + total_pedi
                    subtotal_por_produ.append(
                        calcular_subtotal_producto(int(cantidad), c[9])
                    )
                    break
        try:
            iva = calcular_iva(total_pedi, 12)
            #===========================================================
            insert_cliente(cedula, nombre, apellido, direccion, telefono, email)
            insert_direccion_envio(
                calle_pri,
                calle_sec,
                nume_depa,
                referencia,
                ciudad,
                provincia,
                codi_postal,
            )
            codi_clie = select_cliente_codi_for_cedu_y_nomb(cedula, nombre)            
            codi_dien = select_direccion_envio_codi_for_clpr_y_refe(
                calle_pri, referencia
            )            
            insert_pedido(fecha_pedi, total_pedi, observa, codi_clie, codi_dien)            
            codi_pedi = select_pedido_codi_for_clie_y_dien(codi_clie, codi_dien)                                    
            sleep(0.5)
            for celu, canti in cantidadTemp.items():
                insert_detalle(canti, celu, codi_pedi)
            #===========================================================

            flash("Pedido realizado con exito")
            flash(f"El valor a pagar es de ${total_pedi}")
        except Exception as e:
            print(e)
        return render_template(
            "/pedido/resumen.html",
            subtotales=subtotal_por_produ,
            total=total_pedi,
            iva=iva,
        )

@pedido.route("/actualizar_pedido/<string:codi>", methods=["GET", "POST"])
def actualizar_pedido(codi):
    if request.method == "GET":
        data1 = select_pedido_for_codi(codi)
        data2 = select_detalle_for_codi_pedi(codi)
        return render_template("/pedido/editar.html", pedido=data1, detalle=data2)
    elif request.method == "POST":
        codes = select_detalle_for_codi_pedi(codi)
        fecha_pedido = request.form["fecha_pedido"]
        observ = request.form["observ"]
        total_pedido = 0
        for code in codes:
            comodin = f"celular_{code[6]}"
            cantidad = request.form[comodin]
            total_pedido = total_pedido + (int(cantidad) * code[5])
            try:
                update_detalle(code[1], cantidad, code[6], code[0])
            except Exception as e:
                print(e)
        try:
            update_pedido(
                codi, fecha_pedido, total_pedido, observ, codes[0][7], codes[0][8]
            )
            flash("Pedido editado con exito")
        except Exception as e:
            print(e)
        return redirect(url_for(".Index"))


@pedido.route("/eliminar_pedido/<string:codi>", methods=["POST", "GET"])
def eliminar_pedido(codi: int):
    codes = select_detalle_for_codi_pedi(codi)
    try:
        for code in codes:
            delete_detalle(code[1])
        delete_pedido(codi)
        flash("Pedido eliminado con exito")
    except Exception as e:
        print(e)
    return redirect(url_for(".Index"))


@pedido.route("/eliminar_detalle/<string:codi>", methods=["POST", "GET"])
def eliminar_detalle(codi: int):
    try:
        delete_detalle(codi)
        flash("Celular eliminado con exito")
    except Exception as e:
        print(e)
    return redirect(url_for(".Index"))

@pedido.route('/reporte_pedido', methods=['GET'])
def generar_reporte_ped():
    print(BASE_DIR / "reports")    
    path_wkhtmltopdf = r'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe'
    config = pdfkit.configuration(wkhtmltopdf=path_wkhtmltopdf)
    pdfkit.from_url("http://127.0.0.1:3000/pedido/", BASE_DIR / f"reports/pedido/out.pdf", configuration=config)
    return redirect(url_for('.Index'))

app/templates/direccion_envio/editar.html
{% extends 'base.html' %}
{% block body %}
<div class="container text-center position-absolute top-50 start-50 translate-middle">
    <div class="row align-items-center">        
        <form method="post" action="{{ url_for('.actualizar_direccion_envio', codi=direccion_envio[0]) }}">
            <div class="container text-center">
              <div class="row align-items-start">
                <div class="col">
                  <label for="id_calle_pri" class="form-label">Calle Princpial</label>
                  <input type="text" class="form-control" id="id_calle_pri" name="calle_pri" value="{{direccion_envio[1]}}">
                  <label for="id_calle_sec" class="form-label">Calle Secundaria</label>
                  <input type="text" class="form-control" id="id_calle_sec" name="calle_sec" value="{{direccion_envio[2]}}">
                  <label for="id_nume_depa" class="form-label">Numero de Departamento</label>
                  <input type="text" class="form-control" id="id_nume_depa" name="nume_depa" value="{{direccion_envio[3]}}">
                </div>
                <div class="col">
                  <label for="id_referencia" class="form-label">Referencia</label>
                  <input type="text" class="form-control" id="id_referencia" name="referencia" value="{{direccion_envio[4]}}">   
                  <label for="id_ciudad" class="form-label">Ciudad</label>
                  <input type="text" class="form-control" id="id_ciudad" name="ciudad" value="{{direccion_envio[5]}}">                           
                </div> 
                <div class="col">                  
                  <label for="id_provincia" class="form-label">Provincia</label>
                  <input type="text" class="form-control" id="id_provincia" name="provincia" value="{{direccion_envio[6]}}">  
                  <label for="id_codi_postal" class="form-label">Codigo Postal</label>
                  <input type="text" class="form-control" id="id_codi_postal" name="codi_postal" value="{{direccion_envio[7]}}">          
                </div>                                                    
              </div>
            </div>
            <div id="emailHelp" class="form-text">Los datos de la Direccion de envio serán actualizados.</div>
            <button type="submit" class="btn btn-primary">Editar Datos</button>
          </form>          
    </div>
    <br>
    <a href="{{ url_for('.Index') }}" class="btn btn-primary">Regresar a la Lista</a>
    <a href="{{ url_for('pedido.insertar_pedido') }}" class="btn btn-primary">Regresar al menu Principal</a>
</div>
{% endblock %}

app/templates/direccion_envio/index.html
{% extends 'base.html' %}
{% block body %}

{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages%}
<div class="alert alert-success" role="alert">
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

<div class="container text-center">
  <div class="row align-items-start">
    {% if direcciones_envio %}
    <div class="col">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Calle Princpial</th>
            <th scope="col">Calle Secundaria</th>
            <th scope="col">No. Departamento</th>
            <th scope="col">Referencia</th>
            <th scope="col">Ciudad</th>
            <th scope="col">Provincia</th>
            <th scope="col">Codigo Postal</th>
            <th scope="col">---</th>
            <th scope="col">---</th>
          </tr>
        </thead>
        <tbody>
          {% for direccion_envio in direcciones_envio %}
          <tr>
            <th scope="row" class="text-center">{{ direccion_envio[1] }}</th>
            <td class="text-center">{{ direccion_envio[2] }}</td>
            <td class="text-center">{{ direccion_envio[3] }}</td>
            <td class="text-center">{{ direccion_envio[4] }}</td>
            <td class="text-center">{{ direccion_envio[5] }}</td>
            <td class="text-center">{{ direccion_envio[6] }}</td>
            <td class="text-center">{{ direccion_envio[7] }}</td>
            <td><a href="actualizar_direccion_envio/{{ direccion_envio[0] }}" class="btn btn-primary">Editar</a></td>
            <td><a href="eliminar_direccion_envio/{{ direccion_envio[0] }}" class="btn btn-primary">Eliminar</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% else %}
    <div class="alert alert-info" role="alert">
      Lista Vacia, no hay Direcciones de envio Registrados.
    </div>
    {% endif %}


    <div class="col">
      <div class="position-fixed m-5">
        <h1>Registrar Direccion de Envio</h1>
        <form method="post" action="{{ url_for('.insertar_direccion_envio') }}">
          <div class="container text-center">
            <div class="row align-items-start">
              <label for="id_calle_pri" class="form-label">Calle Princpial</label>
              <input type="text" class="form-control" id="id_calle_pri" name="calle_pri">
              <label for="id_calle_sec" class="form-label">Calle Secundaria</label>
              <input type="text" class="form-control" id="id_calle_sec" name="calle_sec">
              <label for="id_referencia" class="form-label">Referencia</label>
              <input type="text" class="form-control" id="id_referencia" name="referencia">
              <div class="col">
                <label for="id_ciudad" class="form-label">Ciudad</label>
                <input type="text" class="form-control" id="id_ciudad" name="ciudad">
                <label for="id_provincia" class="form-label">Provincia</label>
                <input type="text" class="form-control" id="id_provincia" name="provincia">
              </div>
              <div class="col">
                <label for="id_codi_postal" class="form-label">Codigo Postal</label>
                <input type="text" class="form-control" id="id_codi_postal" name="codi_postal">
                <label for="id_nume_depa" class="form-label">No. Departamento</label>
                <input type="text" class="form-control" id="id_nume_depa" name="nume_depa">
              </div>
            </div>
          </div>
          <div id="emailHelp" class="form-text">Los datos del Direccion de envio seran registrados.</div>
          <button type="submit" class="btn btn-primary">Agregar Datos <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
          </svg></button>
        </form>
      </div>
    </div>
    <a href="{{url_for('direccion_envio.generar_reporte_die')}}">Generar reporte PDF</a>
  </div>
</div>
{% endblock %}