app/routes/auth.py
from flask import (
    Blueprint, flash, redirect, render_template, request, session, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash

from database import select_user
from connections.oracle_conn import Connection

auth = Blueprint('auth', __name__, url_prefix='/auth')

conn = None

@auth.route('/login', methods=('GET', 'POST'))
def login():
    global conn
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']              

        error = None
        try:
            user = select_user(username)                 
        except Exception as e:  
            user = None          
            print(e)

        if user is None:
            error = 'Nombre de Usuario Incorrecto.'
        elif (user[2] != password):
            error = 'Contraseña Incorrecta.'
        if error is None:
            session.clear()
            session['username'] = user[1]
            conn = Connection.getConn(username)
            print(conn)
            return redirect(url_for('pedido.insertar_pedido'))
        flash(error)

    return render_template('auth/login.html')

@auth.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('auth.login'))

app/routes/celular.py
from email.charset import BASE64
from flask import Blueprint, request, render_template, redirect, url_for, flash
from database import select_all_celulares, select_celular_for_codi, insert_celular, update_celular, delete_celular
import pdfkit
from pathlib import Path
import os

BASE_DIR = Path(os.path.join(os.path.dirname(__file__))).parent.parent

celular = Blueprint('celular', __name__, url_prefix='/celular')

@celular.route('/', methods=['GET'])
def Index():
    data = select_all_celulares()    
    return render_template('/celular/index.html', celulares=data)

@celular.route('/insertar_celular', methods=['POST'])
def insertar_celular():
    marca = request.form['marca']
    modelo = request.form['modelo']        
    color = request.form['color']
    camara = request.form['camara']
    pantalla = request.form['pantalla']
    cpu = request.form['cpu']
    ram = request.form['ram']
    almacenamiento = request.form['almacenamiento']
    precio = request.form['precio'] 
    try:
        insert_celular(marca, modelo, color, camara, pantalla, cpu, ram, almacenamiento, precio)
        flash('Celular insertado con exito')
    except Exception as e:        
        print(e)
    return redirect(url_for('.Index'))

@celular.route('/actualizar_celular/<string:codi>', methods=['GET', 'POST'])
def actualizar_celular(codi):
    if( request.method == 'GET'):
        data = select_celular_for_codi(codi)
        return render_template('/celular/editar.html', celular=data)
    elif( request.method == 'POST'):
        marca = request.form['marca']
        modelo = request.form['modelo']        
        color = request.form['color']
        camara = request.form['camara']
        pantalla = request.form['pantalla']
        cpu = request.form['cpu']
        ram = request.form['ram']
        almacenamiento = request.form['almacenamiento']
        precio = request.form['precio']    
        try:    
            update_celular(codi, marca, modelo, color, camara, pantalla, cpu, ram, almacenamiento, precio)
            flash('Celular editado con exito')
        except Exception as e:
            print(e)
        return redirect(url_for('.Index'))

@celular.route('/eliminar_celular/<string:codi>', methods=['POST', 'GET'])
def eliminar_celular(codi:int):    
    try:
        delete_celular(codi)
        flash('Celular eliminado con exito')
    except Exception as e:
        print(e)
        flash('El Celular esta enlazado con un Pedido. Elimine el pedido primero.')
    return redirect(url_for('.Index'))
    
@celular.route('/reporte_celular', methods=['GET'])
def generar_reporte_cel():
    print(BASE_DIR / "reports")    
    path_wkhtmltopdf = r'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe'
    config = pdfkit.configuration(wkhtmltopdf=path_wkhtmltopdf)
    pdfkit.from_url("http://127.0.0.1:3000/celular/", BASE_DIR / f"reports/celular/out.pdf", configuration=config)
    return redirect(url_for('.Index'))

app/routes/cliente.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from database import select_all_clientes, select_cliente_for_codi, insert_cliente, update_cliente, delete_cliente
import pdfkit
from pathlib import Path
import os

BASE_DIR = Path(os.path.join(os.path.dirname(__file__))).parent.parent

cliente = Blueprint('cliente', __name__, url_prefix='/cliente')

@cliente.route('/', methods=['GET'])
def Index():
    data = select_all_clientes()   
    return render_template('/cliente/index.html', clientes=data)

@cliente.route('/insertar_cliente', methods=['POST'])
def insertar_cliente():
    cedula = request.form['cedula']
    nombre = request.form['nombre']        
    apellido = request.form['apellido']
    direccion = request.form['direccion']
    telefono = request.form['telefono']
    email = request.form['email']    
    try:
        insert_cliente(cedula, nombre, apellido, direccion, telefono, email)
        flash('Cliente insertado con exito')
    except Exception as e:        
        flash('Error en el Pedido, vuelva a intentaro y revise los datos.')
        print(e)
    return redirect(url_for('.Index'))

@cliente.route('/actualizar_cliente/<string:codi>', methods=['GET', 'POST'])
def actualizar_cliente(codi):
    if( request.method == 'GET'):
        data = select_cliente_for_codi(codi)
        return render_template('/cliente/editar.html', cliente=data)
    elif( request.method == 'POST'):
        cedula = request.form['cedula']
        nombre = request.form['nombre']        
        apellido = request.form['apellido']
        direccion = request.form['direccion']
        telefono = request.form['telefono']
        email = request.form['email']    
        try:    
            update_cliente(codi, cedula, nombre, apellido, direccion, telefono, email)
            flash('Cliente editado con exito')
        except Exception as e:
            print(e)
        return redirect(url_for('.Index'))

@cliente.route('/eliminar_cliente/<string:codi>', methods=['POST', 'GET'])
def eliminar_cliente(codi:int):    
    try:
        delete_cliente(codi)
        flash('Cliente eliminado con exito')
    except Exception as e:
        flash('El Cliente esta enlazado con un Pedido. Elimine el pedido primero.')
        print(e)
    return redirect(url_for('.Index'))
    
@cliente.route('/reporte_cliente', methods=['GET'])
def generar_reporte_cli():
    print(BASE_DIR / "reports")    
    path_wkhtmltopdf = r'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe'
    config = pdfkit.configuration(wkhtmltopdf=path_wkhtmltopdf)
    pdfkit.from_url("http://127.0.0.1:3000/cliente/", BASE_DIR / f"reports/cliente/out.pdf", configuration=config)
    return redirect(url_for('.Index'))

app/routes/pedido.py
from datetime import datetime
from time import sleep
from flask import Blueprint, request, render_template, redirect, url_for, flash
from database import (
    select_all_celulares,
    select_all_pedidos,
    select_pedido_for_codi,
    select_detalle_for_codi_pedi,
    update_pedido,
    update_detalle,
    delete_detalle,
    delete_pedido,
    select_cliente_codi_for_cedu_y_nomb,
    select_direccion_envio_codi_for_clpr_y_refe,
    select_pedido_codi_for_clie_y_dien,
    insert_cliente,
    insert_direccion_envio,
    insert_pedido,
    insert_detalle,
    calcular_subtotal_producto,
    calcular_iva,
)
import pdfkit
from pathlib import Path
import os

BASE_DIR = Path(os.path.join(os.path.dirname(__file__))).parent.parent

pedido = Blueprint("pedido", __name__, url_prefix="/pedido")


@pedido.route("/", methods=["GET"])
def Index():
    data = select_all_pedidos()
    return render_template("/pedido/index.html", pedidos=data)


@pedido.route("/insertar_pedido", methods=["GET", "POST"])
def insertar_pedido():
    data = select_all_celulares()

    if request.method == "GET":
        return render_template("/pedido/ingresar.html", celulares=data)
    elif request.method == "POST":
        # Datos del cliente
        cedula = request.form["cedula"]
        nombre = request.form["nombre"]
        apellido = request.form["apellido"]
        direccion = request.form["direccion"]
        telefono = request.form["telefono"]
        email = request.form["email"]
        # Datos de la direccion de envio
        calle_pri = request.form["calle_pri"]
        calle_sec = request.form["calle_sec"]
        nume_depa = request.form["nume_depa"]
        referencia = request.form["referencia"]
        ciudad = request.form["ciudad"]
        provincia = request.form["provincia"]
        codi_postal = request.form["codi_postal"]
        # Datos del Pedido
        total_pedi = 0
        subtotal_por_produ = []
        cantidadTemp = {}
        fecha_pedi = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        selected_celu = request.form.getlist("celulares")
        observa = request.form["observa"]
        # Celulares selccionados y cantidad
        for celu in selected_celu:
            comodin = f"celular_{celu}"
            cantidad = request.form[comodin]
            cantidadTemp[celu] = cantidad
            for c in data:
                if c[0] == int(celu):
                    total_pedi = (c[9] * int(cantidad)) + total_pedi
                    subtotal_por_produ.append(
                        calcular_subtotal_producto(int(cantidad), c[9])
                    )
                    break
        try:
            iva = calcular_iva(total_pedi, 12)
            #===========================================================
            insert_cliente(cedula, nombre, apellido, direccion, telefono, email)
            insert_direccion_envio(
                calle_pri,
                calle_sec,
                nume_depa,
                referencia,
                ciudad,
                provincia,
                codi_postal,
            )
            codi_clie = select_cliente_codi_for_cedu_y_nomb(cedula, nombre)            
            codi_dien = select_direccion_envio_codi_for_clpr_y_refe(
                calle_pri, referencia
            )            
            insert_pedido(fecha_pedi, total_pedi, observa, codi_clie, codi_dien)            
            codi_pedi = select_pedido_codi_for_clie_y_dien(codi_clie, codi_dien)                                    
            sleep(0.5)
            for celu, canti in cantidadTemp.items():
                insert_detalle(canti, celu, codi_pedi)
            #===========================================================

            flash("Pedido realizado con exito")
            flash(f"El valor a pagar es de ${total_pedi}")
        except Exception as e:
            print(e)
        return render_template(
            "/pedido/resumen.html",
            subtotales=subtotal_por_produ,
            total=total_pedi,
            iva=iva,
        )

@pedido.route("/actualizar_pedido/<string:codi>", methods=["GET", "POST"])
def actualizar_pedido(codi):
    if request.method == "GET":
        data1 = select_pedido_for_codi(codi)
        data2 = select_detalle_for_codi_pedi(codi)
        return render_template("/pedido/editar.html", pedido=data1, detalle=data2)
    elif request.method == "POST":
        codes = select_detalle_for_codi_pedi(codi)
        fecha_pedido = request.form["fecha_pedido"]
        observ = request.form["observ"]
        total_pedido = 0
        for code in codes:
            comodin = f"celular_{code[6]}"
            cantidad = request.form[comodin]
            total_pedido = total_pedido + (int(cantidad) * code[5])
            try:
                update_detalle(code[1], cantidad, code[6], code[0])
            except Exception as e:
                print(e)
        try:
            update_pedido(
                codi, fecha_pedido, total_pedido, observ, codes[0][7], codes[0][8]
            )
            flash("Pedido editado con exito")
        except Exception as e:
            print(e)
        return redirect(url_for(".Index"))


@pedido.route("/eliminar_pedido/<string:codi>", methods=["POST", "GET"])
def eliminar_pedido(codi: int):
    codes = select_detalle_for_codi_pedi(codi)
    try:
        for code in codes:
            delete_detalle(code[1])
        delete_pedido(codi)
        flash("Pedido eliminado con exito")
    except Exception as e:
        print(e)
    return redirect(url_for(".Index"))


@pedido.route("/eliminar_detalle/<string:codi>", methods=["POST", "GET"])
def eliminar_detalle(codi: int):
    try:
        delete_detalle(codi)
        flash("Celular eliminado con exito")
    except Exception as e:
        print(e)
    return redirect(url_for(".Index"))

@pedido.route('/reporte_pedido', methods=['GET'])
def generar_reporte_ped():
    print(BASE_DIR / "reports")    
    path_wkhtmltopdf = r'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe'
    config = pdfkit.configuration(wkhtmltopdf=path_wkhtmltopdf)
    pdfkit.from_url("http://127.0.0.1:3000/pedido/", BASE_DIR / f"reports/pedido/out.pdf", configuration=config)
    return redirect(url_for('.Index'))

app/templates/base.html
<!DOCTYPE html>
<html lang="es" data-bs-theme="dark">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pedidos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
        <div class="container-fluid">
            <img src="{{ url_for('static', filename='logo_edismacc.jpg') }}" alt="" class="rounded img-fluid" width="40" height="40" style="margin: 3px 10px 3px 10px;">
            <a class="navbar-brand" href="{{ url_for('pedido.insertar_pedido') }}">Realizar Pedido <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
              </svg></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" aria-current="page" href="{{ url_for('pedido.Index') }}">Pedidos <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-shop-window" viewBox="0 0 16 16">
                        <path d="M2.97 1.35A1 1 0 0 1 3.73 1h8.54a1 1 0 0 1 .76.35l2.609 3.044A1.5 1.5 0 0 1 16 5.37v.255a2.375 2.375 0 0 1-4.25 1.458A2.371 2.371 0 0 1 9.875 8 2.37 2.37 0 0 1 8 7.083 2.37 2.37 0 0 1 6.125 8a2.37 2.37 0 0 1-1.875-.917A2.375 2.375 0 0 1 0 5.625V5.37a1.5 1.5 0 0 1 .361-.976l2.61-3.045zm1.78 4.275a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 1 0 2.75 0V5.37a.5.5 0 0 0-.12-.325L12.27 2H3.73L1.12 5.045A.5.5 0 0 0 1 5.37v.255a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0zM1.5 8.5A.5.5 0 0 1 2 9v6h12V9a.5.5 0 0 1 1 0v6h.5a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1H1V9a.5.5 0 0 1 .5-.5zm2 .5a.5.5 0 0 1 .5.5V13h8V9.5a.5.5 0 0 1 1 0V13a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V9.5a.5.5 0 0 1 .5-.5z"/>
                      </svg></a>
                    <a class="nav-link" href="{{ url_for('celular.Index') }}">Celular <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-phone" viewBox="0 0 16 16">
                        <path d="M11 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h6zM5 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H5z"/>
                        <path d="M8 14a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                      </svg></a>
                    <a class="nav-link" href="{{ url_for('cliente.Index') }}">Cliente <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                        <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z"/>
                      </svg></a>
                    <a class="nav-link" href="{{ url_for('direccion_envio.Index') }}">Direccion de Envio <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-compass" viewBox="0 0 16 16">
                        <path d="M8 16.016a7.5 7.5 0 0 0 1.962-14.74A1 1 0 0 0 9 0H7a1 1 0 0 0-.962 1.276A7.5 7.5 0 0 0 8 16.016zm6.5-7.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
                        <path d="m6.94 7.44 4.95-2.83-2.83 4.95-4.949 2.83 2.828-4.95z"/>
                      </svg></a>
                </div>
            </div>
        
            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <li class="ms-3"><a class="text-muted" href="#">
                    <img src="{{ url_for('static', filename='/icons/whatsapp.png') }}" alt="">  
                </a></li>
                <li class="ms-3"><a class="text-muted" href="#">
                    <img src="{{ url_for('static', filename='/icons/instagram.png') }}" alt="">  
                </a></li>
                <li class="ms-3"><a class="text-muted" href="#">
                    <img src="{{ url_for('static', filename='/icons/facebook.png') }}" alt="">  
                </a></li>
                <a href="{{url_for('auth.logout')}}" class="nav-link">Cerrar Sesion</a>
            </ul>

        </div>

        

    </nav>
    {% block body%}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>

</html>